# -*- coding: utf-8 -*-
"""TugasPythonLanjutan_Hari_15_Raka_Rizkya_Hadi_Putra

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g0uYm1JJz4tB97K19Edcdsu3ELhq2_17
"""

# Import library yang dibutuhkan
from openpyxl import load_workbook
import json

# Load file xlsx ke dalam workbook
filename = "pokemon_db.xlsx"
data = load_workbook(filename=filename)

# Memeriksa data yang telah dimuat
sheet = data.active
print(data.sheetnames)
print(sheet)

# Membuat dictionary di dalam list
pokemon_data = []
for row in range(len(sheet['A'])):
  if sheet[row+1][0].value == "Name":
    continue
  
  # Membuat dictionary untuk tiap pokemon
  pokemon = {}
  pokemon['Nama']=sheet[row+1][0].value
  pokemon['Tipe']=sheet[row+1][1].value
  pokemon['Total']=sheet[row+1][2].value
  pokemon['HP']=sheet[row+1][3].value
  pokemon['Attack']=sheet[row+1][4].value
  pokemon['Defense']=sheet[row+1][5].value
  pokemon['SpAttack']=sheet[row+1][6].value
  pokemon['SpDefense']=sheet[row+1][7].value
  pokemon['Speed']=sheet[row+1][8].value

  # Memasukkan dictionary ke dalam list
  pokemon_data.append(pokemon)

# Menampilkan dictionary dalam list
print(pokemon_data)

with open("Raka.json", "w") as outfile:  
  json.dump(pokemon_data, outfile)

