# -*- coding: utf-8 -*-
"""TugasPythonLanjutan_Hari_7_Raka Rizkya Hadi Putra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11NeOOablYDgYK75Zb2ozVTaoj0LdaE4x
"""

# Import library yang dibutuhkan
import tweepy

# Menyiapkan key untuk mengakses API twitter
consumer_key = "onqGw4kpoQl8V9civEIDTzwct"
consumer_secret = "GwoBtWhEuuQQqmthLMnCTY0JexAwjLjFgUNvqTLoFcL9I1eCDk"
access_token = "1288079487284858880-a9IzuV48TwVfjmN3Uh024hGCrCWAql"
access_token_secret = "3Dmek80uNr6yVBW1YQ496GOgsXo0IgUX9Na6gYOSMnMwT"

# Set up authorization menggunakan key yang telah disiapkan
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)

# Mengambil data Tweet akun Presiden Jokowi
nama = "jokowi"
jumlahtweet = 200
hasil = api.user_timeline(id=nama, count=jumlahtweet)

# Memasukkan data tweet ke dalam sebuah list
cuit = []
for tweet in hasil:
  cuit.append(tweet.text)

# Memisahkan antara tweet mengenai Covid dan bukan mengenai Covid
covid = [s for s in cuit if "Covid" in s]
noncovid = [s for s in cuit if "Covid" not in s]
print("Jumlah tweet Jokowi mengenai Covid: " + str(len(covid)))
print("Jumlah tweet Jokowi bukan mengenai Covid: " + str(len(noncovid)))